import { useEffect,useMemo,useRef,useState } from 'react'
import { ArrowUp,BookOpen,Box,Check,ChevronRight,Circle,File,FileLock2,FolderOpen,History,LoaderCircle,NotebookPen,PanelLeftClose,PanelLeftOpen,Paperclip,Pause,Pencil,Play,Plus,RotateCcw,Search,ShieldCheck,Square,Upload,Wrench,X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { api } from './api'
import CoworkAgentPanel from './CoworkAgentPanel'
import type { CoworkAgent,CoworkAgentGroup,CoworkSession,CoworkSessionSummary,CoworkSkill } from './coworkTypes'
import './cowork.css'

const statusLabel:Record<string,string>={draft:'草稿',planned:'已规划',running:'运行中',paused:'已暂停',completed:'已完成',cancelled:'已取消',failed:'失败',pending:'待执行'}
const resourceLabel:Record<string,string>={folder:'文件夹',file:'文件',paper:'论文',note:'笔记',project:'项目',experiment:'实验',study:'专题调研',deepwiki:'DeepWiki',reading_history:'阅读记录'}

export default function CoworkPage({ onOpenAssistant:_onOpenAssistant }: { onOpenAssistant: () => void }) {
  const [sessions,setSessions]=useState<CoworkSessionSummary[]>([]),[session,setSession]=useState<CoworkSession|null>(null)
  const [skills,setSkills]=useState<CoworkSkill[]>([]),[goal,setGoal]=useState(''),[message,setMessage]=useState(''),[notice,setNotice]=useState('')
  const [detail,setDetail]=useState<'concise'|'rich'>('rich'),[effort,setEffort]=useState<'low'|'medium'|'high'>('medium'),[busy,setBusy]=useState(false)
  const [permissionOpen,setPermissionOpen]=useState(false),[manualPath,setManualPath]=useState(''),[paperQuery,setPaperQuery]=useState(''),[paperCandidates,setPaperCandidates]=useState<any[]>([])
  const [editingPlan,setEditingPlan]=useState(false),[planDraft,setPlanDraft]=useState<Array<{title:string;description:string}>>([])
  const [agentGroup,setAgentGroup]=useState<CoworkAgentGroup|null>(null)
  const [historyCollapsed,setHistoryCollapsed]=useState(()=>localStorage.getItem('papermorrow-cowork-history-collapsed')==='1')
  const [skillOpen,setSkillOpen]=useState(false),[skillDraft,setSkillDraft]=useState(''),[skillPreview,setSkillPreview]=useState<any>(null)
  const endRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null),goalRef=useRef<HTMLTextAreaElement>(null)
  const loadSessions=async()=>{const rows=await api<CoworkSessionSummary[]>('/api/cowork/sessions');setSessions(rows)}
  useEffect(()=>{void Promise.all([loadSessions(),api<CoworkSkill[]>('/api/cowork/skills').then(setSkills)]).catch(error=>setNotice(error.message))},[])
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[session?.messages.length])
  useEffect(()=>{if(!session){setAgentGroup(null);return}if(session.agent_group)setAgentGroup(session.agent_group);else void api<CoworkAgentGroup>(`/api/cowork/sessions/${session.id}/agents`).then(setAgentGroup).catch(()=>setAgentGroup(null))},[session?.id])
  const refresh=async(id=session?.id)=>{if(!id)return;const current=await api<CoworkSession>(`/api/cowork/sessions/${id}`);setSession(current);await loadSessions()}
  const create=async()=>{if(!goal.trim()||busy)return;setBusy(true);setNotice('');try{const created=await api<CoworkSession>('/api/cowork/sessions',{method:'POST',body:JSON.stringify({goal:goal.trim(),response_detail:detail,thinking_effort:effort})});setSession(created);setGoal('');await loadSessions()}catch(error){setNotice(error instanceof Error?error.message:'创建任务失败')}finally{setBusy(false)}}
  const action=async(name:string)=>{if(!session||busy)return;setBusy(true);try{const updated=await api<CoworkSession>(`/api/cowork/sessions/${session.id}/${name}`,{method:'POST'});setSession(updated);if(updated.agent_group)setAgentGroup(updated.agent_group);else void api<CoworkAgentGroup>(`/api/cowork/sessions/${session.id}/agents`).then(setAgentGroup).catch(()=>{});await loadSessions()}catch(error){setNotice(error instanceof Error?error.message:'操作失败')}finally{setBusy(false)}}
  const send=async()=>{if(!session||!message.trim()||busy)return;const value=message.trim();setMessage('');setBusy(true);try{const updated=await api<CoworkSession>(`/api/cowork/sessions/${session.id}/messages`,{method:'POST',body:JSON.stringify({content:value,attachments:[]})});setSession(updated);await loadSessions()}catch(error){setNotice(error instanceof Error?error.message:'发送失败')}finally{setBusy(false)}}
  const selectSession=async(id:string)=>{setBusy(true);try{setSession(await api<CoworkSession>(`/api/cowork/sessions/${id}`))}finally{setBusy(false)}}
  const grantPath=async(path:string,type:'file'|'folder')=>{if(!session||!path.trim())return;try{const updated=await api<CoworkSession>(`/api/cowork/sessions/${session.id}/grants`,{method:'POST',body:JSON.stringify({resource_type:type,resource_scope:path.trim(),can_read:true,can_write:false,duration:'session'})});setSession(updated);setManualPath('');setPermissionOpen(false)}catch(error){setNotice(error instanceof Error?error.message:'授权失败')}}
  const pickFolder=async()=>{const path=await window.pywebview?.api?.choose_folder?.();if(path)await grantPath(path,'folder');else setPermissionOpen(true)}
  const pickFiles=async()=>{const paths=await window.pywebview?.api?.choose_files?.();if(paths?.length){for(const path of paths)await grantPath(path,'file')}else fileRef.current?.click()}
  const localFiles=(files:FileList|null)=>{if(!files?.length)return;setNotice('浏览器不会暴露真实路径；桌面版可直接授权文件。当前仅记录附件名称。');setMessage(value=>`${value}${value?'\n':''}附件：${[...files].map(file=>file.name).join('、')}`)}
  const revoke=async(id:string)=>{if(!session)return;setSession(await api<CoworkSession>(`/api/cowork/sessions/${session.id}/grants/${id}`,{method:'DELETE'}))}
  const searchPaper=async()=>{if(paperQuery.trim().length<2)return;setBusy(true);try{const result=await api<{items:any[]}>(`/api/library/search?q=${encodeURIComponent(paperQuery.trim())}&limit=8`);setPaperCandidates(result.items)}catch(error){setNotice(error instanceof Error?error.message:'检索失败')}finally{setBusy(false)}}
  const importPaper=async(candidate:any)=>{try{await api('/api/library/import',{method:'POST',body:JSON.stringify(candidate)});setPaperCandidates(items=>items.map(item=>item.identity===candidate.identity?{...item,in_library:true}:item));setNotice(`已导入《${candidate.title}》；永久去重规则由学习库执行。`)}catch(error){setNotice(error instanceof Error?error.message:'导入失败')}}
  const beginPlanEdit=()=>{const task=session?.tasks[session.tasks.length-1];setPlanDraft((task?.steps||[]).map(step=>({title:step.title,description:step.description})));setEditingPlan(true)}
  const savePlan=async()=>{if(!session||planDraft.some(step=>!step.title.trim()))return;setBusy(true);try{setSession(await api<CoworkSession>(`/api/cowork/sessions/${session.id}/plan`,{method:'PUT',body:JSON.stringify({steps:planDraft})}));setEditingPlan(false);setNotice('计划已更新，后续步骤将按新内容执行。')}catch(error){setNotice(error instanceof Error?error.message:'更新计划失败')}finally{setBusy(false)}}
  const saveReply=async(text:string)=>{if(!session||!text.trim())return;const title=`${session.title} · Cowork`;try{const created=await api<any>('/api/notes',{method:'POST',body:JSON.stringify({title,document_format:'markdown',editor_mode:'standard',origin:'standalone',content:`# ${title}\n\n## AI 回复\n\n${text.trim()}\n\n> 来源：Cowork 会话 ${session.id}\n`,paper_ids:[]})});window.dispatchEvent(new CustomEvent('papermorrow:note-updated',{detail:created}));setNotice(`已新建笔记《${title}》`)}catch(error){setNotice(error instanceof Error?error.message:'保存到笔记失败')}}
  const stopAgent=async(agent:CoworkAgent)=>{if(!session||busy)return;setBusy(true);try{setAgentGroup(await api<CoworkAgentGroup>(`/api/cowork/sessions/${session.id}/agents/${agent.id}/stop`,{method:'POST'}));setNotice(`已停止专家 Agent「${agent.display_name}」，主任务与其他专家不受影响。`)}catch(error){setNotice(error instanceof Error?error.message:'停止专家 Agent 失败')}finally{setBusy(false)}}
  const stopAllAgents=async()=>{if(!session||busy)return;if(!agentGroup?.agents.length)return assembleAgents();if(agentGroup.agents.some(agent=>agent.status==='queued'||agent.status==='paused'))return runAgents();setBusy(true);try{setAgentGroup(await api<CoworkAgentGroup>(`/api/cowork/sessions/${session.id}/agents/stop-all`,{method:'POST'}));setNotice('已停止全部专家 Agent；主 Agent 保留现有结果与检查点。')}catch(error){setNotice(error instanceof Error?error.message:'停止专家 Agent 群失败')}finally{setBusy(false)}}
  const assembleAgents=async()=>{if(!session||busy)return;const context_refs=session.grants.filter(item=>['file','paper','note','project','experiment','study','deepwiki'].includes(item.resource_type)).map(item=>({resource_type:item.resource_type,resource_id:item.resource_type==='file'?(item.normalized_path||item.resource_scope):item.resource_scope,source_id:`grant:${item.id}`,label:item.resource_scope,evidence_scope:item.resource_type==='paper'?'abstract':'user_record'}));setBusy(true);try{setAgentGroup(await api<CoworkAgentGroup>(`/api/cowork/sessions/${session.id}/agents/assemble`,{method:'POST',body:JSON.stringify({roles:['literature_evidence','research_synthesis','project_planning'],context_refs})}));setNotice('已召集三个受控科研专家。请先检查各自资料范围与预算，再点击运行。')}catch(error){setNotice(error instanceof Error?error.message:'召集专家失败')}finally{setBusy(false)}}
  const runAgents=async()=>{if(!session||busy)return;setBusy(true);setNotice('');try{const updated=await api<CoworkAgentGroup>(`/api/cowork/sessions/${session.id}/agents/run`,{method:'POST'});setAgentGroup(updated);setNotice(updated.agents.some(agent=>agent.status==='paused')?'未配置模型，专家已安全暂停；配置 LLM Profile 后可继续。':'本批专家已完成或安全停止；请展开专家卡核对来源、限制和下一步。')}catch(error){setNotice(error instanceof Error?error.message:'专家运行失败')}finally{setBusy(false)}}
  const toggleHistory=()=>setHistoryCollapsed(value=>{localStorage.setItem('papermorrow-cowork-history-collapsed',value?'0':'1');return !value})
  const useStarter=(value:string,label:string)=>{setGoal(value);setNotice(`已载入“${label}”任务模板，可继续补充资料和交付要求。`);window.setTimeout(()=>goalRef.current?.focus(),0)}
  const previewSkill=async()=>{try{const parsed=JSON.parse(skillDraft);setSkillPreview(await api('/api/cowork/skills/preview',{method:'POST',body:JSON.stringify(parsed)}));setNotice('Skill 安全预览已通过；确认来源与权限后即可导入。')}catch(error){setSkillPreview(null);setNotice(error instanceof Error?error.message:'Skill 清单格式无效')}}
  const importSkill=async()=>{try{const parsed=JSON.parse(skillDraft);const created=await api<CoworkSkill>('/api/cowork/skills/import',{method:'POST',body:JSON.stringify(parsed)});setSkills(items=>[...items,created]);setSkillOpen(false);setSkillDraft('');setSkillPreview(null);setNotice(`已导入 Skill「${created.name}」，仅允许使用清单中声明的本地工具。`)}catch(error){setNotice(error instanceof Error?error.message:'导入 Skill 失败')}}
  const activeTask=session?.tasks[session.tasks.length-1],completed=activeTask?.steps.filter(step=>step.status==='completed').length||0,total=activeTask?.steps.length||0
  const canContinue=session&&['planned','paused','running'].includes(session.status)
  const latestSources=useMemo(()=>session?.messages.flatMap(item=>item.sources)||[],[session])

  return <div className={`cowork-shell ${historyCollapsed?'history-collapsed':''}`}>
    <aside className="cowork-history"><header><button className="cowork-history-toggle" aria-label={historyCollapsed?'展开任务侧栏':'收起任务侧栏'} title={historyCollapsed?'展开任务侧栏':'收起任务侧栏'} onClick={toggleHistory}>{historyCollapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><div><History/><span><strong>最近任务</strong><small>{sessions.length ? `${sessions.length} 个研究任务` : '从一个目标开始'}</small></span></div><button aria-label="新建任务" title="新建任务" onClick={()=>setSession(null)}><Plus/></button></header><div>{sessions.length?sessions.map(item=><button key={item.id} title={historyCollapsed?item.title:undefined} className={session?.id===item.id?'active':''} onClick={()=>selectSession(item.id)}><i className={item.status}/><span><strong>{item.title}</strong><small>{statusLabel[item.status]||item.status} · {new Date(item.updated_at).toLocaleDateString()}</small></span><ChevronRight/></button>):<p className="cowork-history-empty">任务记录会显示在这里，方便随时继续。</p>}</div><footer><ShieldCheck/><span><strong>资料由你选择</strong><small>添加文件或文件夹后开始协作</small></span></footer></aside>
    {!session?<main className="cowork-start"><div className="cowork-start-inner"><div className="cowork-intro"><span>AI RESEARCH WORKSPACE</span><h1>从研究问题到<br/>可检查的成果</h1><p>描述你想完成的工作，添加需要参考的论文或文件。AI 会先整理步骤，再与你一起完成检索、分析和写作。</p></div><section className="cowork-goal-box"><textarea ref={goalRef} autoFocus value={goal} onChange={event=>setGoal(event.target.value)} placeholder="例如：比较三篇 Agent Memory 论文的记忆机制，整理证据表并生成组会汇报大纲" onKeyDown={event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey))void create()}}/><div className="cowork-goal-actions"><button onClick={pickFiles}><Paperclip/>添加文件</button><button onClick={pickFolder}><FolderOpen/>选择资料夹</button><span/><label><span>回答</span><select value={detail} onChange={event=>setDetail(event.target.value as any)}><option value="concise">简洁</option><option value="rich">详细</option></select></label><label><span>分析</span><select value={effort} onChange={event=>setEffort(event.target.value as any)}><option value="low">快速</option><option value="medium">标准</option><option value="high">深入</option></select></label><button className="cowork-send" aria-label="开始任务" disabled={!goal.trim()||busy} onClick={create}>{busy?<LoaderCircle className="spin"/>:<ArrowUp/>}</button></div></section><div className="cowork-starters"><button onClick={()=>useStarter('比较我选择的论文，区分论文事实、作者主张与 AI 推断，定位可核查证据并生成引用检查表。','梳理文献证据')}><i><BookOpen/></i><div><strong>梳理文献证据</strong><span>比较论文、定位原文依据并检查引用</span></div></button><button onClick={()=>useStarter('比较我选择的实验记录，引用实验编号，识别异常、变量差异与证据缺口，并生成复现准备清单。','分析实验记录')}><i><Wrench/></i><div><strong>分析实验记录</strong><span>对比结果、发现异常并准备复现清单</span></div></button><button onClick={()=>useStarter('根据我选择的论文和项目资料，生成可编辑的研究汇报大纲、报告结构与数据表，并标注每项来源。','生成研究材料')}><i><Box/></i><div><strong>生成研究材料</strong><span>创建汇报大纲、研究报告和数据表</span></div></button></div><div className="cowork-skill-strip"><button onClick={()=>setSkillOpen(true)}><Check/>{skills.length || 7} 项科研 Skill · 预览与导入</button><span><ShieldCheck/>每一步都可暂停和检查</span></div></div></main>:
    <main className="cowork-workspace"><header className="cowork-workspace-head"><div><span>RESEARCH COWORK · {statusLabel[session.status]||session.status}</span><h2>{session.title}</h2></div><div>{session.status==='running'?<button onClick={()=>action('pause')}><Pause/>暂停</button>:canContinue?<button className="primary" onClick={()=>action(session.status==='paused'?'resume':'run-next')}><Play/>{session.status==='paused'?'继续':'运行下一步'}</button>:null}{session.status!=='cancelled'&&session.status!=='completed'&&<button className="danger" onClick={()=>action('cancel')}><Square/>停止</button>}</div></header>
      <div className="cowork-permission-bar"><ShieldCheck/><span><strong>当前授权</strong>{session.grants.length?session.grants.map(item=>`${resourceLabel[item.resource_type]||item.resource_type}：${item.resource_scope}`).join(' · '):'尚未授权额外资料，仅可使用会话内容'}</span><button onClick={()=>setPermissionOpen(true)}>调整</button></div>
      <div className="cowork-columns"><section className="cowork-thread"><div className="cowork-plan-card"><header><div><strong>任务计划</strong><span>{completed}/{total} 已完成</span><button onClick={editingPlan?()=>setEditingPlan(false):beginPlanEdit}>{editingPlan?<X/>:<Pencil/>}{editingPlan?'取消':'编辑'}</button></div><i><b style={{width:`${total?completed/total*100:0}%`}}/></i></header>{editingPlan?<div className="cowork-plan-editor">{planDraft.map((step,index)=><label key={index}><span>{index+1}</span><div><input aria-label={`步骤 ${index+1} 标题`} value={step.title} onChange={event=>setPlanDraft(items=>items.map((item,i)=>i===index?{...item,title:event.target.value}:item))}/><textarea aria-label={`步骤 ${index+1} 说明`} value={step.description} onChange={event=>setPlanDraft(items=>items.map((item,i)=>i===index?{...item,description:event.target.value}:item))}/></div></label>)}<button className="primary" disabled={busy||planDraft.some(step=>!step.title.trim())} onClick={savePlan}><Check/>保存计划</button></div>:activeTask?.steps.map(step=><article key={step.id} className={step.status}><span>{step.status==='completed'?<Check/>:step.status==='running'?<LoaderCircle className="spin"/>:<Circle/>}</span><div><strong>{step.position}. {step.title}</strong><p>{step.result_summary||step.description}</p></div>{['failed','paused','cancelled'].includes(step.status)&&step.retry_count<2&&<button onClick={()=>api<CoworkSession>(`/api/cowork/sessions/${session.id}/steps/${step.id}/retry`,{method:'POST'}).then(setSession)}><RotateCcw/>重试</button>}</article>)}</div>
        <div className="cowork-messages">{session.messages.map(item=><article key={item.id} className={`cowork-message ${item.role}`}><header><span>{item.role==='assistant'?'PaperMorrow Agent':'你'}</span><time>{new Date(item.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></header>{item.blocks.map((block,index)=><section className="cowork-message-block" key={index}><div>{block.type==='markdown'?<ReactMarkdown remarkPlugins={[remarkGfm]}>{block.text||''}</ReactMarkdown>:block.text}</div>{item.role==='assistant'&&block.text&&<button className="cowork-save" onClick={()=>saveReply(block.text||'')}><NotebookPen/>将这段新建为笔记</button>}</section>)}{item.sources.length>0&&<footer>{item.sources.map((source,index)=><span key={index}>[{source.id||index+1}] {source.title}</span>)}</footer>}</article>)}{busy&&<div className="cowork-busy"><LoaderCircle className="spin"/>Agent 正在推进一个可验证步骤…</div>}<div ref={endRef}/></div>
        <div className="cowork-compose"><textarea value={message} onChange={event=>setMessage(event.target.value)} placeholder="补充要求、修订计划或询问当前进度…" onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}}/><div><button onClick={pickFiles}><Paperclip/>附件</button><button onClick={pickFolder}><FolderOpen/>文件夹</button><span>Enter 发送 · Shift + Enter 换行</span><button className="cowork-send" disabled={!message.trim()||busy} onClick={send}><ArrowUp/></button></div></div></section>
        <aside className="cowork-inspector"><CoworkAgentPanel group={agentGroup} busy={busy} onStopAgent={agent=>void stopAgent(agent)} onStopAll={()=>void stopAllAgents()}/><section><header><FileLock2/><strong>资料与权限</strong></header>{session.grants.length?session.grants.map(item=><article key={item.id}><span>{resourceLabel[item.resource_type]||item.resource_type}</span><strong>{item.resource_scope}</strong><small>{item.can_write?'可读写':'只读'} · {item.duration==='session'?'仅本次':'长期'}</small><button aria-label="撤销授权" onClick={()=>revoke(item.id)}><X/></button></article>):<p>没有额外资料授权。Agent 不会读取你的全部笔记、项目或文件。</p>}</section><section><header><Wrench/><strong>工具与审批</strong></header>{session.tool_calls.length?session.tool_calls.map(item=><article key={item.id}><span className={`risk ${item.risk_level}`}>{item.risk_level}</span><strong>{item.tool_name}</strong><small>{item.approval_status} · {item.status}</small></article>):<p>尚未调用工具。写入与外部操作会先出现审批预览。</p>}</section><section><header><Box/><strong>产物</strong></header>{session.artifacts.length?session.artifacts.map(item=><article key={item.id}><File/><strong>{item.title}</strong><small>{item.type}</small></article>):<p>生成的 PPT、报告、表格、笔记与导入论文会集中在这里。</p>}</section><section><header><Search/><strong>论文候选预览</strong></header><div className="cowork-paper-search"><input value={paperQuery} onChange={event=>setPaperQuery(event.target.value)} onKeyDown={event=>event.key==='Enter'&&searchPaper()} placeholder="DOI、arXiv URL 或标题"/><button onClick={searchPaper}><Search/></button></div>{paperCandidates.map(item=><article className="paper-candidate" key={item.identity}><strong>{item.title}</strong><small>{item.doi||item.arxiv_id||item.source} · {item.abstract?'仅摘要':'仅元数据'}</small><button disabled={item.in_library} onClick={()=>importPaper(item)}>{item.in_library?'已在学习库':'预览后导入'}</button></article>)}</section><section><header><BookOpen/><strong>来源</strong></header>{latestSources.length?latestSources.map((item,index)=><article key={index}><strong>[{item.id||index+1}] {item.title}</strong><small>{item.locator||'会话来源'}</small></article>):<p>引用论文事实时，来源编号与证据范围会显示在这里。</p>}</section></aside></div></main>}
    {permissionOpen&&session&&<div className="cowork-modal" onMouseDown={()=>setPermissionOpen(false)}><section onMouseDown={event=>event.stopPropagation()}><header><div><ShieldCheck/><span><strong>调整本任务权限</strong><small>默认只读、仅本会话；写入仍需单独审批</small></span></div><button onClick={()=>setPermissionOpen(false)}><X/></button></header><button className="picker" onClick={pickFolder}><FolderOpen/><span><strong>选择文件夹</strong><small>允许读取根目录内的非隐藏资料，阻止符号链接逃逸</small></span></button><button className="picker" onClick={pickFiles}><File/><span><strong>选择文件</strong><small>密钥、.env 与凭据文件始终拒绝</small></span></button><label>或输入本机绝对路径<div><input value={manualPath} onChange={event=>setManualPath(event.target.value)} placeholder="/Users/name/research/project"/><button onClick={()=>grantPath(manualPath,'folder')}>只读授权</button></div></label><p>论文、笔记、项目与实验的对象级权限将在引用选择器中逐项加入；不会提供“永久允许删除”。</p></section></div>}
    {skillOpen&&<div className="cowork-modal" onMouseDown={()=>setSkillOpen(false)}><section className="cowork-skill-modal" onMouseDown={event=>event.stopPropagation()}><header><div><Upload/><span><strong>科研 Skill</strong><small>先预览来源、许可证、工具权限与安全边界，再决定是否导入</small></span></div><button onClick={()=>setSkillOpen(false)}><X/></button></header><div className="cowork-skill-list">{skills.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>v{item.version} · {item.license}</span></div><p>{item.description}</p><small>{item.allowed_tools.length?`工具：${item.allowed_tools.join('、')}`:'不调用工具'} · 来源：{item.source}</small></article>)}</div><label>粘贴 Skill JSON 清单<textarea value={skillDraft} onChange={event=>{setSkillDraft(event.target.value);setSkillPreview(null)}} placeholder={'{"name":"my-research-skill","description":"...","version":"1.0.0","allowed_tools":["library.search"],"source":"https://...","license":"MIT","instructions":"# 工作流程\\n..."}'}/></label>{skillPreview&&<div className="skill-preview"><strong>{skillPreview.name} · v{skillPreview.version}</strong><span>{skillPreview.license} · {skillPreview.instruction_characters} 字</span><p>{skillPreview.description}</p><small>无 Shell · 无默认联网 · 无未授权文件读取</small></div>}<footer><button onClick={previewSkill} disabled={!skillDraft.trim()}>安全预览</button><button className="primary" onClick={importSkill} disabled={!skillPreview}>确认导入</button></footer></section></div>}
    <input ref={fileRef} type="file" multiple hidden onChange={event=>localFiles(event.target.files)}/>{notice&&<div className="cowork-toast" onClick={()=>setNotice('')}><Check/>{notice}</div>}
  </div>
}
