import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, Download, FlaskConical, Layers3, Plus, Power, RefreshCw, Upload } from 'lucide-react'
import { api } from './api'
import type { DomainPack } from './types'
import './domains.css'

const steps = ['基础信息','数据源','Venue 与论文类型','评分与证据','影响指标','搜索预览']
const blank = {slug:'',name_zh:'',name_en:'',description:'',enabled:true,source_adapters:[{adapter:'arxiv',enabled:true}],search_templates:['{keywords}'],keywords:[],exclusions:[],category_codes:[],venue_rules:[],paper_types:['journal_article','conference_paper','preprint','review'],scoring_weights:{relevance:.3,venue:.2,evidence:.2,recency:.15,citation_percentile:.1,openness:.05},evidence_rules:{require_verifiable_source:true,preprint_risk:true},analysis_prompt:'区分论文事实、作者主张与 AI 判断，并给出可核验证据。',review_prompt:'生成可追溯到论文的结构化综述。',citation_config:{use_field_normalized_percentile:true},impact_config:{allow_custom_metrics:true,require_source_url:true},metrics:[]}
const lines = (value:string) => value.split(/[,，\n]/).map(item=>item.trim()).filter(Boolean)

export default function DomainPacksPage(){
  const [packs,setPacks]=useState<DomainPack[]>([]),[editing,setEditing]=useState<any|null>(null),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[preview,setPreview]=useState<any|null>(null),[importText,setImportText]=useState('')
  const load=()=>api<DomainPack[]>('/api/domain-packs').then(setPacks)
  useEffect(()=>{load()},[])
  const builtin=useMemo(()=>packs.filter(p=>p.is_builtin),[packs]), custom=useMemo(()=>packs.filter(p=>!p.is_builtin),[packs])
  const edit=(pack?:DomainPack)=>{setEditing(pack?{...pack,keywords_text:pack.keywords.join('\n'),exclusions_text:pack.exclusions.join('\n'),categories_text:pack.category_codes.join('\n'),sources_text:pack.source_adapters.map(s=>`${s.adapter}${s.enabled===false?' (停用)':''}`).join('\n'),venues_text:JSON.stringify(pack.venue_rules,null,2),paper_types_text:pack.paper_types.join('\n'),weights_text:JSON.stringify(pack.scoring_weights,null,2),evidence_text:JSON.stringify(pack.evidence_rules,null,2),metrics_text:pack.metrics.map(m=>`${m.name} | ${m.value} | ${m.year} | ${m.source_url}`).join('\n')}:{...blank,keywords_text:'',exclusions_text:'',categories_text:'',sources_text:'arxiv',venues_text:'[]',paper_types_text:blank.paper_types.join('\n'),weights_text:JSON.stringify(blank.scoring_weights,null,2),evidence_text:JSON.stringify(blank.evidence_rules,null,2),metrics_text:''});setStep(0);setPreview(null);setMessage('')}
  const payload=()=>{const sources=lines(editing.sources_text).map((value:string)=>({adapter:value.replace(/\s*\(停用\)$/,'').trim(),enabled:!value.endsWith('(停用)')}));const metrics=lines(editing.metrics_text).map((row:string)=>{const [name,value,year,source_url]=row.split('|').map(x=>x.trim());return {name,value:Number(value),year:Number(year),source_url}});return {...editing,source_adapters:sources,keywords:lines(editing.keywords_text),exclusions:lines(editing.exclusions_text),category_codes:lines(editing.categories_text),venue_rules:JSON.parse(editing.venues_text||'[]'),paper_types:lines(editing.paper_types_text),scoring_weights:JSON.parse(editing.weights_text||'{}'),evidence_rules:JSON.parse(editing.evidence_text||'{}'),metrics}}
  const save=async()=>{setBusy(true);try{const body=payload();await api(editing.id?`/api/domain-packs/${editing.id}`:'/api/domain-packs',{method:editing.id?'PUT':'POST',body:JSON.stringify(body)});setEditing(null);await load()}catch(e){setMessage(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}
  const testSources=async()=>{setBusy(true);try{const results=[];for(const config of payload().source_adapters)results.push(await api('/api/domain-packs/test-source',{method:'POST',body:JSON.stringify({config})}));setMessage(results.map((r:any)=>r.message).join('；'))}catch(e){setMessage(e instanceof Error?e.message:'连接失败')}finally{setBusy(false)}}
  const doPreview=async()=>{if(!editing.id)return setMessage('请先保存专业，再运行搜索预览');setPreview(await api(`/api/domain-packs/${editing.id}/search-preview`,{method:'POST',body:JSON.stringify({query:editing.name_en})}))}
  const toggle=async(pack:DomainPack)=>{await api(`/api/domain-packs/${pack.id}`,{method:'PUT',body:JSON.stringify({enabled:!pack.enabled})});await load()}
  const exportPack=async(pack:DomainPack)=>{const data=await api(`/api/domain-packs/${pack.id}/export`);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${pack.slug}.domain-pack.json`;a.click();URL.revokeObjectURL(url)}
  const importPack=async()=>{try{await api('/api/domain-packs/import',{method:'POST',body:JSON.stringify(JSON.parse(importText))});setImportText('');await load()}catch(e){setMessage(e instanceof Error?e.message:'导入失败')}}
  const cards=(items:DomainPack[])=>items.map(pack=><article key={pack.id} className={!pack.enabled?'disabled':''}><div><span>{pack.is_builtin?'内置专业':`自定义 · v${pack.version}`}</span><h3>{pack.name_zh}<small>{pack.name_en}</small></h3><p>{pack.description}</p><footer>{pack.source_adapters.filter(s=>s.enabled!==false).map(s=><i key={s.adapter}>{s.adapter}</i>)}</footer></div><aside><button onClick={()=>edit(pack)}>配置</button><button title="导出" onClick={()=>exportPack(pack)}><Download size={15}/></button><button title={pack.enabled?'停用':'启用'} onClick={()=>toggle(pack)}><Power size={15}/></button></aside></article>)
  return <section className="page-content domain-page"><header className="domain-hero"><div><span className="section-kicker">DOMAIN PACKS</span><h2>研究专业与评价体系</h2><p>选择适合你的学科配置，让论文来源、评价标准和证据要求更贴合研究习惯。</p></div><button className="primary" onClick={()=>edit()}><Plus size={17}/>自定义专业</button></header>
    <div className="domain-section"><h3>内置专业 <small>按各学科的研究传统与证据标准组织</small></h3><div className="domain-grid">{cards(builtin)}</div></div><div className="domain-section"><h3>自定义专业</h3><div className="domain-grid">{custom.length?cards(custom):<div className="domain-empty">创建自己的专业规则，让数据源、评价标准和研究方向更贴合你的工作。</div>}</div></div>
    <div className="domain-import"><Upload/><div><strong>导入 Domain Pack</strong><p>粘贴从 PaperMorrow 导出的 JSON；普通论文网站只作为参考，不会启用通用爬虫。</p></div><textarea value={importText} onChange={e=>setImportText(e.target.value)} placeholder="粘贴 Domain Pack JSON"/><button disabled={!importText.trim()} onClick={importPack}>导入</button></div>
    {editing&&<div className="domain-wizard-backdrop"><div className="domain-wizard"><header><div><span>{editing.id?'配置专业':'新建专业'}</span><h2>{editing.name_zh||'自定义 Domain Pack'}</h2></div><button onClick={()=>setEditing(null)}>×</button></header><nav>{steps.map((label,index)=><button key={label} className={step===index?'active':''} onClick={()=>setStep(index)}><i>{index+1}</i>{label}</button>)}</nav><main>
      {step===0&&<div className="wizard-form"><label>Slug<input disabled={Boolean(editing.id)} value={editing.slug} onChange={e=>setEditing({...editing,slug:e.target.value})}/></label><label>中文名<input value={editing.name_zh} onChange={e=>setEditing({...editing,name_zh:e.target.value})}/></label><label>英文名<input value={editing.name_en} onChange={e=>setEditing({...editing,name_en:e.target.value})}/></label><label className="span-2">说明<textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label></div>}
      {step===1&&<div><p className="wizard-help">每行一个已支持适配器：arxiv、semantic_scholar、openalex、crossref、pubmed、europe_pmc、rss_atom。追加“(停用)”可保留配置但不检索。</p><textarea className="code-area" value={editing.sources_text} onChange={e=>setEditing({...editing,sources_text:e.target.value})}/><button className="secondary" disabled={busy} onClick={testSources}>{busy?<RefreshCw className="spin"/>:<FlaskConical/>}连接测试</button></div>}
      {step===2&&<div className="wizard-form"><label>分类代码<textarea value={editing.categories_text} onChange={e=>setEditing({...editing,categories_text:e.target.value})}/></label><label>论文类型<textarea value={editing.paper_types_text} onChange={e=>setEditing({...editing,paper_types_text:e.target.value})}/></label><label className="span-2">Venue 规则 JSON（name、aliases、paper_types、level）<textarea className="code-area" value={editing.venues_text} onChange={e=>setEditing({...editing,venues_text:e.target.value})}/></label></div>}
      {step===3&&<div className="wizard-form"><label>关键词<textarea value={editing.keywords_text} onChange={e=>setEditing({...editing,keywords_text:e.target.value})}/></label><label>排除词<textarea value={editing.exclusions_text} onChange={e=>setEditing({...editing,exclusions_text:e.target.value})}/></label><label>评分权重 JSON<textarea className="code-area" value={editing.weights_text} onChange={e=>setEditing({...editing,weights_text:e.target.value})}/></label><label>证据规则 JSON<textarea className="code-area" value={editing.evidence_text} onChange={e=>setEditing({...editing,evidence_text:e.target.value})}/></label></div>}
      {step===4&&<div><p className="wizard-help">每行：指标名称 | 数值 | 年份 | 来源 URL。不得填写无法核验的“最新 JIF”。</p><textarea className="code-area" value={editing.metrics_text} onChange={e=>setEditing({...editing,metrics_text:e.target.value})} placeholder="领域归一化引用百分位 | 92 | 2025 | https://..."/></div>}
      {step===5&&<div><p className="wizard-help">预览只展示可复核查询，不发送真实网络请求。</p><button className="secondary" onClick={doPreview}><FlaskConical/>生成搜索预览</button>{preview&&<pre>{JSON.stringify(preview,null,2)}</pre>}</div>}{message&&<div className="wizard-message">{message}</div>}
    </main><footer><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}><ChevronLeft/>上一步</button><span>{step+1} / {steps.length}</span>{step<steps.length-1?<button onClick={()=>setStep(step+1)}>下一步<ChevronRight/></button>:<button className="primary" disabled={busy||!editing.slug||!editing.name_zh||!editing.name_en} onClick={save}>{busy?<RefreshCw className="spin"/>:<Check/>}保存专业</button>}</footer></div></div>}
  </section>
}
