import { useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, Bot, Check, ChevronRight, CircleDashed, FlaskConical, GitCompareArrows, Plus, Send, X } from 'lucide-react'
import { api } from './api'
import './experiments.css'

type Metric={id?:number;name:string;value:number;step?:number|null;split?:string;unit?:string;is_primary?:boolean;recorded_at?:string}
type Experiment={id:number;title:string;objective:string;hypothesis:string;experiment_type:string;status:string;parent_experiment_id?:number|null;config:Record<string,unknown>;environment:Record<string,unknown>;dataset_version:string;code_reference:string;command:string;observations:string;conclusion:string;started_at?:string|null;ended_at?:string|null;created_at:string;updated_at:string;metrics:Metric[];artifacts:any[]}
type Summary={timeline:any[];metric_series:Record<string,any[]>|any[];status_counts:Record<string,number>;total?:number}

const statusLabels:Record<string,string>={planned:'计划中',running:'运行中',completed:'已完成',failed:'未达到预期',paused:'已暂停'}
const experimentTypes=[['run','常规实验'],['baseline','基线'],['ablation','消融实验'],['reproduction','复现实验'],['exploration','探索实验']]

export default function ExperimentsPanel({projectId}:{projectId:number}){
  const [experiments,setExperiments]=useState<Experiment[]>([])
  const [summary,setSummary]=useState<Summary|null>(null)
  const [creating,setCreating]=useState(false)
  const [active,setActive]=useState<Experiment|null>(null)
  const [busy,setBusy]=useState(false)
  const [question,setQuestion]=useState('结合全部实验记录，概括目前进展、关键变量和最值得优先验证的下一步。')
  const [analysis,setAnalysis]=useState<{answer:string;sources:string[];used_llm:boolean}|null>(null)
  const [draft,setDraft]=useState({title:'',objective:'',hypothesis:'',experiment_type:'run',status:'planned',dataset_version:'',code_reference:'',config:'{}',environment:'{}'})
  const [metric,setMetric]=useState({name:'',value:'',unit:'',split:'',is_primary:true})
  const load=async()=>{const [items,stats]=await Promise.all([api<Experiment[]>(`/api/projects/${projectId}/experiments`),api<Summary>(`/api/projects/${projectId}/experiments/summary`)]);setExperiments(items);setSummary(stats);setActive(current=>current?items.find(item=>item.id===current.id)||items[0]||null:items[0]||null)}
  useEffect(()=>{load().catch(()=>undefined)},[projectId])
  const create=async()=>{setBusy(true);try{let config={},environment={};try{config=JSON.parse(draft.config||'{}');environment=JSON.parse(draft.environment||'{}')}catch{throw new Error('参数与环境需要使用有效的 JSON 格式')}const item=await api<Experiment>(`/api/projects/${projectId}/experiments`,{method:'POST',body:JSON.stringify({...draft,config,environment})});setCreating(false);setDraft({title:'',objective:'',hypothesis:'',experiment_type:'run',status:'planned',dataset_version:'',code_reference:'',config:'{}',environment:'{}'});setActive(item);await load()}finally{setBusy(false)}}
  const addMetric=async()=>{if(!active||!metric.name||metric.value==='')return;await api(`/api/projects/${projectId}/experiments/${active.id}/metrics`,{method:'POST',body:JSON.stringify({metrics:[{...metric,value:Number(metric.value)}]})});setMetric({name:'',value:'',unit:'',split:'',is_primary:true});await load()}
  const analyze=async()=>{if(!question.trim())return;setBusy(true);try{setAnalysis(await api(`/api/projects/${projectId}/experiments/analyze`,{method:'POST',body:JSON.stringify({question})}))}finally{setBusy(false)}}
  const chartSeries=useMemo(()=>normalizeSeries(summary?.metric_series),[summary])
  return <section className="experiment-workbench">
    <header className="experiment-head"><div><span>EXPERIMENT LEDGER</span><h3>实验记录与进展分析</h3><p>按时间保留配置、指标、观察和结论，帮助你看清每次改动带来的真实变化。</p></div><button onClick={()=>setCreating(true)}><Plus/>记录实验</button></header>
    {creating&&<div className="experiment-create"><header><strong>新实验</strong><button onClick={()=>setCreating(false)}><X/></button></header><div className="experiment-form"><label className="wide">实验名称<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：学习率与探索比例消融"/></label><label>实验类型<select value={draft.experiment_type} onChange={e=>setDraft({...draft,experiment_type:e.target.value})}>{experimentTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>状态<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(statusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="wide">目标<textarea value={draft.objective} onChange={e=>setDraft({...draft,objective:e.target.value})} placeholder="这次实验需要回答什么问题？"/></label><label className="wide">假设<textarea value={draft.hypothesis} onChange={e=>setDraft({...draft,hypothesis:e.target.value})} placeholder="预期哪项改变会带来怎样的结果？"/></label><label>数据版本<input value={draft.dataset_version} onChange={e=>setDraft({...draft,dataset_version:e.target.value})} placeholder="数据集 / split / version"/></label><label>代码版本<input value={draft.code_reference} onChange={e=>setDraft({...draft,code_reference:e.target.value})} placeholder="commit、branch 或运行标识"/></label><label className="wide">参数 JSON<textarea className="code" value={draft.config} onChange={e=>setDraft({...draft,config:e.target.value})}/></label><label className="wide">环境 JSON<textarea className="code" value={draft.environment} onChange={e=>setDraft({...draft,environment:e.target.value})}/></label></div><footer><button className="secondary" onClick={()=>setCreating(false)}>取消</button><button disabled={!draft.title.trim()||busy} onClick={create}>{busy?<CircleDashed className="spin"/>:<Check/>}保存实验</button></footer></div>}
    <div className="experiment-overview"><article><FlaskConical/><span>累计实验</span><strong>{summary?.total??experiments.length}</strong><small>{Object.entries(summary?.status_counts||{}).map(([key,value])=>`${statusLabels[key]||key} ${value}`).join(' · ')||'从第一条实验开始建立可追溯过程'}</small></article><article className="metric-chart-card"><div><BarChart3/><span>结果变化</span><strong>{chartSeries.name||'等待指标'}</strong></div><MetricChart points={chartSeries.points}/></article></div>
    <div className="experiment-grid"><div className="experiment-timeline"><header><Activity/><strong>实验时间线</strong></header>{experiments.length?experiments.map((item,index)=><button key={item.id} className={active?.id===item.id?'active':''} onClick={()=>setActive(item)}><i/><div><span>{new Date(item.started_at||item.created_at).toLocaleDateString('zh-CN')} · {experimentTypes.find(type=>type[0]===item.experiment_type)?.[1]||item.experiment_type}</span><strong>{item.title}</strong><small>{item.objective||item.hypothesis||'尚未补充目标与假设'}</small><em className={`experiment-status ${item.status}`}>{statusLabels[item.status]||item.status}</em></div><ChevronRight/></button>):<div className="experiment-empty"><FlaskConical/><strong>还没有实验记录</strong><p>先记录实验目标和配置，后续结果会自动汇集到同一条时间线上。</p></div>}</div><div className="experiment-detail">{active?<><header><div><span>EXP-{String(active.id).padStart(3,'0')}</span><h4>{active.title}</h4></div><em className={`experiment-status ${active.status}`}>{statusLabels[active.status]||active.status}</em></header><div className="experiment-claims"><div><span>实验目标</span><p>{active.objective||'尚未记录'}</p></div><div><span>待验证假设</span><p>{active.hypothesis||'尚未记录'}</p></div><div><span>观察</span><p>{active.observations||'等待实验结果'}</p></div><div><span>当前结论</span><p>{active.conclusion||'尚未形成结论'}</p></div></div><section className="metric-entry"><header><strong>指标记录</strong><small>每次追加都会保留时间和实验来源</small></header><div><input value={metric.name} onChange={e=>setMetric({...metric,name:e.target.value})} placeholder="指标名称"/><input type="number" value={metric.value} onChange={e=>setMetric({...metric,value:e.target.value})} placeholder="数值"/><input value={metric.unit} onChange={e=>setMetric({...metric,unit:e.target.value})} placeholder="单位"/><button onClick={addMetric}><Plus/>添加</button></div><div className="metric-chips">{active.metrics?.map((item,index)=><span key={item.id||index}><b>{item.name}</b>{item.value}{item.unit}</span>)}</div></section></>:<div className="experiment-empty"><GitCompareArrows/><strong>选择一条实验查看详情</strong><p>配置、结果和结论会在这里并列展示，便于对比实验变化。</p></div>}</div></div>
    <section className="experiment-agent"><header><div><Bot/><div><span>EXPERIMENT AGENT</span><strong>实验进展分析</strong></div></div><small>分析覆盖项目的完整实验账本；每项判断标注实验来源或 AI 推断。</small></header>{analysis&&<article><p>{analysis.answer}</p><footer>{analysis.sources?.map((source:any,index)=><span key={typeof source==='string'?source:index}>{typeof source==='string'?source:`EXP-${source.experiment_id}${source.title?` · ${source.title}`:''}`}</span>)}<em>{analysis.used_llm?'模型综合分析':'本地统计摘要'}</em></footer></article>}<div><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="询问实验变化、失败模式、消融结果或下一步验证计划"/><button disabled={busy||!question.trim()} onClick={analyze}>{busy?<CircleDashed className="spin"/>:<Send/>}</button></div></section>
  </section>
}

function normalizeSeries(series:Summary['metric_series']|undefined){if(!series)return{name:'',points:[] as number[]};if(Array.isArray(series)){const first=series[0];if(!first)return{name:'',points:[]};if(typeof first==='number')return{name:'主要指标',points:series};const name=first.name||first.metric||'主要指标';return{name,points:series.map((item:any)=>Number(item.value??item.y??0))}}const entry=Object.entries(series)[0];if(!entry)return{name:'',points:[]};return{name:entry[0],points:(entry[1]||[]).map((item:any)=>Number(typeof item==='number'?item:item.value??item.y??0))}}
function MetricChart({points}:{points:number[]}){if(!points.length)return <div className="metric-chart-empty">记录指标后显示趋势</div>;const width=360,height=92,pad=8,min=Math.min(...points),max=Math.max(...points),range=max-min||1;const coords=points.map((value,index)=>({x:pad+index*(width-pad*2)/Math.max(1,points.length-1),y:height-pad-(value-min)/range*(height-pad*2)}));return <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="实验指标变化曲线"><path d={`M ${coords.map(point=>`${point.x} ${point.y}`).join(' L ')}`}/>{coords.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r="3"><title>{points[index]}</title></circle>)}</svg>}
