import { useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, Check, CircleDashed, FileText, Plus, Presentation, Sparkles, Trash2, X } from 'lucide-react'
import { api } from './api'
import './presentation-outline.css'

type Source={id:string;type:'paper'|'note'|'experiment'|'project'|'wiki'|'inference';title:string;authors?:string[];year?:number;locator?:string}
type OutlineSlide={id:string;title:string;purpose:string;key_message:string;points:string[];source_refs:string[]}
type Draft={id:number;title:string;kind:string;language:string;outline:{schemaVersion:string;title:string;kind:string;language:string;slides:OutlineSlide[]};sources:Source[];status:string;download_url?:string|null;error?:string|null}

const kinds=[['lab-meeting','组会汇报','适合阶段进展、讨论与下一步'],['paper-report','论文汇报','围绕问题、方法、实验和局限'],['research-progress','科研进度','突出阶段目标与结果变化'],['experiment-report','实验总结','对比实验、消融和失败经验'],['literature-review','文献综述','整理研究路线、争议和空白']] as const

export default function PresentationOutlineEditor({noteId,onClose}:{noteId:number;onClose:()=>void}){
  const [draft,setDraft]=useState<Draft|null>(null)
  const [kind,setKind]=useState('lab-meeting'),[slideCount,setSlideCount]=useState(10),[instructions,setInstructions]=useState('')
  const [blank,setBlank]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const [selected,setSelected]=useState(0)
  const current=draft?.outline.slides[selected]
  const sourceGroups=useMemo(()=>{const groups:Record<string,Source[]>={note:[],paper:[],experiment:[],project:[],wiki:[],inference:[]};draft?.sources.forEach(source=>(groups[source.type]||groups.note).push(source));return groups},[draft])
  const start=async()=>{setBusy(true);setNotice('');try{const result=await api<Draft>('/api/presentations/outlines',{method:'POST',body:JSON.stringify({note_id:noteId,kind,slide_count:slideCount,instructions,use_ai:!blank,blank})});setDraft(result);setSelected(0)}catch(error){setNotice(error instanceof Error?error.message:'大纲生成失败')}finally{setBusy(false)}}
  const updateSlide=(values:Partial<OutlineSlide>)=>{if(!draft)return;const slides=draft.outline.slides.map((slide,index)=>index===selected?{...slide,...values}:slide);setDraft({...draft,outline:{...draft.outline,slides}})}
  const addSlide=()=>{if(!draft)return;const slide:OutlineSlide={id:`outline-${Date.now()}`,title:'新页面',purpose:'论证',key_message:'',points:[],source_refs:[]};const slides=[...draft.outline.slides.slice(0,selected+1),slide,...draft.outline.slides.slice(selected+1)];setDraft({...draft,outline:{...draft.outline,slides}});setSelected(selected+1)}
  const removeSlide=()=>{if(!draft||draft.outline.slides.length<=1)return;const slides=draft.outline.slides.filter((_,index)=>index!==selected);setDraft({...draft,outline:{...draft.outline,slides}});setSelected(Math.max(0,selected-1))}
  const move=(direction:-1|1)=>{if(!draft)return;const target=selected+direction;if(target<0||target>=draft.outline.slides.length)return;const slides=[...draft.outline.slides];[slides[selected],slides[target]]=[slides[target],slides[selected]];setDraft({...draft,outline:{...draft.outline,slides}});setSelected(target)}
  const toggleSource=(id:string)=>{if(!current)return;updateSlide({source_refs:current.source_refs.includes(id)?current.source_refs.filter(item=>item!==id):[...current.source_refs,id]})}
  const save=async()=>{if(!draft)return;setBusy(true);try{const saved=await api<Draft>(`/api/presentations/${draft.id}/outline`,{method:'PUT',body:JSON.stringify({title:draft.title,instructions,outline:draft.outline})});setDraft(saved);setNotice('大纲已保存，可以继续编辑或生成演示文稿。')}catch(error){setNotice(error instanceof Error?error.message:'大纲保存失败')}finally{setBusy(false)}}
  const generate=async()=>{if(!draft)return;setBusy(true);setNotice('正在编译版式并检查引用…');try{const saved=await api<Draft>(`/api/presentations/${draft.id}/outline`,{method:'PUT',body:JSON.stringify({title:draft.title,instructions,outline:draft.outline})});setDraft(saved);const result=await api<Draft>(`/api/presentations/${draft.id}/generate`,{method:'POST'});setDraft(result);setNotice('演示文稿已生成，所有文字、图表和形状均可继续编辑。')}catch(error){setNotice(error instanceof Error?error.message:'演示文稿生成失败')}finally{setBusy(false)}}
  return <div className="presentation-backdrop"><section className="presentation-studio">
    <header><div className="presentation-brand"><div><span>演示文稿</span><h2>{draft?'编辑大纲':'新建科研汇报'}</h2></div></div><button aria-label="关闭" onClick={onClose}><X/></button></header>
    {!draft?<main className="presentation-start"><div className="presentation-intro"><h3>创建演示文稿大纲</h3><p>先选择汇报类型。可以让 AI 根据当前笔记和引用资料生成初稿，也可以从空白大纲开始。</p><p className="presentation-scope-note">系统会完成叙事结构、文本、引用和基础数据展示；生成后请人工校对，并按需补充论文 framework、实验结果可视化、样例图等关键图片。</p></div><div className="presentation-kind-grid">{kinds.map(([id,label,description])=><button key={id} className={kind===id?'selected':''} onClick={()=>setKind(id)}><i>{kind===id&&<Check/>}</i><span><strong>{label}</strong><small>{description}</small></span></button>)}</div><label>汇报要求（可选）<textarea value={instructions} onChange={event=>setInstructions(event.target.value)} placeholder="例如：15 分钟组会，重点讨论方法局限和后续实验。"/></label><div className="presentation-options"><label>目标页数<select value={slideCount} onChange={event=>setSlideCount(Number(event.target.value))}>{[6,8,10,12,15,20].map(value=><option key={value} value={value}>{value} 页左右</option>)}</select></label><button className={blank?'active':''} onClick={()=>setBlank(!blank)}><FileText/>{blank?'空白大纲':'AI 生成初稿'}</button></div>{notice&&<p className="presentation-notice error">{notice}</p>}<button className="presentation-primary" disabled={busy} onClick={start}>{busy?<CircleDashed className="spin"/>:<Sparkles/>}{blank?'创建大纲':'生成大纲'}</button></main>:<main className="presentation-editor">
      <aside className="presentation-pages"><header><div><span>页面</span><strong>{draft.outline.slides.length}</strong></div><button aria-label="添加页面" onClick={addSlide}><Plus/></button></header><div>{draft.outline.slides.map((slide,index)=><button key={slide.id} className={selected===index?'active':''} onClick={()=>setSelected(index)}><em>{index+1}</em><div><strong>{slide.title}</strong><span>{slide.key_message||slide.purpose}</span><small>{slide.source_refs.length ? `${slide.source_refs.length} 条引用` : '无引用'}</small></div></button>)}</div></aside>
      <section className="presentation-outline-form">{current&&<><header><div><span>第 {selected+1} 页 / 共 {draft.outline.slides.length} 页</span><strong>页面大纲</strong></div><div><button title="上移" disabled={selected===0} onClick={()=>move(-1)}><ArrowUp/></button><button title="下移" disabled={selected===draft.outline.slides.length-1} onClick={()=>move(1)}><ArrowDown/></button><button title="删除" disabled={draft.outline.slides.length<=1} onClick={removeSlide}><Trash2/></button></div></header><label>页面标题<input value={current.title} onChange={event=>updateSlide({title:event.target.value})}/></label><div className="presentation-row"><label>页面作用<input value={current.purpose} onChange={event=>updateSlide({purpose:event.target.value})} placeholder="开场、论证、对比或总结"/></label><label>核心结论<input value={current.key_message} onChange={event=>updateSlide({key_message:event.target.value})} placeholder="这一页需要传达的结论"/></label></div><label>页面要点<textarea value={current.points.join('\n')} onChange={event=>updateSlide({points:event.target.value.split('\n').filter(Boolean).slice(0,6)})} placeholder="每行一条，建议不超过 5 条"/></label><section className="presentation-page-sources"><header><strong>本页引用</strong><span>显示在脚注和演讲备注中</span></header><div>{current.source_refs.map(id=>{const source=draft.sources.find(item=>item.id===id);return <button key={id} onClick={()=>toggleSource(id)}><span>{id}</span><strong>{source?.title||'未知来源'}</strong><X/></button>})}{!current.source_refs.length&&<p>从右侧来源列表中添加笔记、论文或实验记录。</p>}</div></section></>}</section>
      <aside className="presentation-sources"><header><div><span>引用来源</span><strong>点击添加到本页</strong></div></header>{Object.entries(sourceGroups).filter(([,items])=>items.length).map(([type,items])=><section key={type}><h4>{type==='paper'?'论文':type==='note'?'笔记':type==='experiment'?'实验记录':type==='project'?'研究项目':type}</h4>{items.map(source=><button key={source.id} className={current?.source_refs.includes(source.id)?'selected':''} onClick={()=>toggleSource(source.id)}><div><span>{source.id}</span><strong>{source.title}</strong><small>{[source.authors?.slice(0,2).join('、'),source.year,source.locator].filter(Boolean).join(' · ')}</small></div>{current?.source_refs.includes(source.id)&&<Check/>}</button>)}</section>)}</aside>
    </main>}
    {draft&&<footer><div>{notice&&<span className="presentation-notice">{notice}</span>}<small>生成前会检查空标题、无效引用和版式边界；关键 framework 与实验可视化可在生成后继续插入。</small></div><button onClick={save} disabled={busy}>保存大纲</button>{draft.download_url&&<a href={draft.download_url} target="_blank" rel="noreferrer">下载 PPTX</a>}<button className="presentation-primary" onClick={generate} disabled={busy}>{busy?<CircleDashed className="spin"/>:<Presentation/>}生成 PPTX</button></footer>}
  </section></div>
}
