import { useEffect, useState } from 'react'
import { Check, Compass, Pencil, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import { api } from './api'
import type { DomainPack, ResearchProfile } from './types'

const domainLabels:Record<string,string> = {ai:'AI（完整优化）',computer:'计算机科学',physics:'物理',math:'数学','life-sciences':'生命科学','clinical-medicine':'临床医学','chemistry-materials':'化学与材料','economics-finance':'经济学与金融'}
const emptyDraft={name:'',domain:'ai',domain_pack_id:null,description:'',positive_keywords:'',negative_keywords:'',seed_papers:'',relevance_weight:.55,recency_weight:.25,exploration_ratio:.2}

export default function ResearchProfiles({profiles,onChanged}:{profiles:ResearchProfile[];onChanged:()=>Promise<void>}){
  const [draft,setDraft]=useState<any|null>(null),[editing,setEditing]=useState<number|null>(null),[busy,setBusy]=useState(false),[packs,setPacks]=useState<DomainPack[]>([])
  useEffect(()=>{api<DomainPack[]>('/api/domain-packs').then(items=>setPacks(items.filter(item=>item.enabled))).catch(()=>{})},[])
  const startEdit=(profile:ResearchProfile)=>{setEditing(profile.id);setDraft({...profile,positive_keywords:profile.positive_keywords.join(', '),negative_keywords:profile.negative_keywords.join(', '),seed_papers:profile.seed_papers.join('\n')})}
  const save=async()=>{if(!draft?.name.trim()||draft.description.trim().length<8)return;setBusy(true);try{const split=(value:string)=>value.split(/[,，\n]/).map(item=>item.trim()).filter(Boolean);const pack=packs.find(item=>item.id===Number(draft.domain_pack_id));const payload={...draft,domain:pack?.slug||draft.domain,domain_pack_id:pack?.id||draft.domain_pack_id||null,positive_keywords:split(draft.positive_keywords),negative_keywords:split(draft.negative_keywords),seed_papers:draft.seed_papers.split('\n').map((item:string)=>item.trim()).filter(Boolean)};['id','enabled','created_at','updated_at','domain_pack'].forEach(key=>delete payload[key]);await api(editing?`/api/research-profiles/${editing}`:'/api/research-profiles',{method:editing?'PUT':'POST',body:JSON.stringify(payload)});setDraft(null);setEditing(null);await onChanged()}finally{setBusy(false)}}
  const remove=async(profile:ResearchProfile)=>{if(!window.confirm(`删除研究方向“${profile.name}”？历史推荐仍会保留。`))return;await api(`/api/research-profiles/${profile.id}`,{method:'DELETE'});await onChanged()}
  return <div className="settings-card full research-profile-card"><header><Compass/><div><h3>研究方向</h3><p>添加你长期关注的问题和关键词，让每日推荐更贴近当前研究重点。</p></div><button className="secondary" onClick={()=>{setEditing(null);setDraft({...emptyDraft})}}><Plus size={15}/>新增方向</button></header>
    {draft&&<div className="direction-editor"><div className="direction-editor-head"><strong>{editing?'编辑研究方向':'建立研究方向'}</strong><button className="icon-button" onClick={()=>{setDraft(null);setEditing(null)}}><X size={16}/></button></div><div className="direction-form"><label>方向名称<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例如：自进化 LLM"/></label><label>研究专业<select value={draft.domain_pack_id||''} onChange={e=>{const pack=packs.find(item=>item.id===Number(e.target.value));setDraft({...draft,domain_pack_id:pack?.id||null,domain:pack?.slug||draft.domain})}}><option value="">旧领域兼容</option>{packs.map(pack=><option key={pack.id} value={pack.id}>{pack.name_zh} · {pack.name_en}</option>)}</select></label><label className="span-2">研究描述<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="描述关注的问题、方法边界和不希望混入的近似概念。"/></label><label>关键词与别名<input value={draft.positive_keywords} onChange={e=>setDraft({...draft,positive_keywords:e.target.value})}/></label><label>排除概念<input value={draft.negative_keywords} onChange={e=>setDraft({...draft,negative_keywords:e.target.value})}/></label><label className="span-2">种子论文链接（每行一篇）<textarea className="short" value={draft.seed_papers} onChange={e=>setDraft({...draft,seed_papers:e.target.value})}/></label></div><div className="direction-sliders"><label>方向关联度 <strong>{Math.round(draft.relevance_weight*100)}%</strong><input type="range" min=".2" max=".8" step=".05" value={draft.relevance_weight} onChange={e=>setDraft({...draft,relevance_weight:Number(e.target.value),recency_weight:Math.min(Number(draft.recency_weight),.95-Number(e.target.value))})}/></label><label>发布时间 <strong>{Math.round(draft.recency_weight*100)}%</strong><input type="range" min=".05" max=".6" step=".05" value={draft.recency_weight} onChange={e=>setDraft({...draft,recency_weight:Math.min(Number(e.target.value),.95-Number(draft.relevance_weight))})}/></label><label>广度探索配额 <strong>{Math.round(draft.exploration_ratio*100)}%</strong><input type="range" min="0" max=".5" step=".05" value={draft.exploration_ratio} onChange={e=>setDraft({...draft,exploration_ratio:Number(e.target.value)})}/></label></div><div className="editor-actions"><button className="secondary" onClick={()=>setDraft(null)}>取消</button><button className="primary" disabled={busy||!draft.name||draft.description.length<8} onClick={save}>{busy?<RefreshCw className="spin" size={15}/>:<Check size={15}/>}保存方向</button></div></div>}
    <div className="direction-list">{profiles.length?profiles.map(profile=><article key={profile.id}><div className={`domain-dot ${profile.domain}`}/><div><span>{profile.domain_pack?.name_zh||domainLabels[profile.domain]||profile.domain}</span><strong>{profile.name}</strong><p>{profile.description}</p><small>关联 {Math.round(profile.relevance_weight*100)}% · 时效 {Math.round(profile.recency_weight*100)}% · 探索 {Math.round(profile.exploration_ratio*100)}%</small></div><button className="icon-button" title="编辑" onClick={()=>startEdit(profile)}><Pencil size={15}/></button><button className="icon-button danger" title="删除" onClick={()=>remove(profile)}><Trash2 size={15}/></button></article>):<div className="direction-empty">还没有研究方向。广度推荐仍可正常使用。</div>}</div>
  </div>
}
