import { useEffect,useMemo,useRef,useState } from 'react'
import { ArrowUp,BookOpen,Box,Check,ChevronRight,Circle,File,FileLock2,FolderOpen,History,LoaderCircle,NotebookPen,Paperclip,Pause,Play,Plus,RotateCcw,Search,ShieldCheck,Square,Trash2,Wrench,X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { api } from './api'
import type { CoworkSession,CoworkSessionSummary,CoworkSkill } from './coworkTypes'
import './cowork.css'

const statusLabel:Record<string,string>={draft:'草稿',planned:'已规划',running:'运行中',paused:'已暂停',completed:'已完成',cancelled:'已取消',failed:'失败',pending:'待执行'}
const resourceLabel:Record<string,string>={folder:'文件夹',file:'文件',paper:'论文',note:'笔记',project:'项目',experiment:'实验',study:'专题调研',deepwiki:'DeepWiki',reading_history:'阅读记录'}

export default function CoworkPage({ onOpenAssistant:_onOpenAssistant }: { onOpenAssistant: () => void }) {
  const [sessions,setSessions]=useState<CoworkSessionSummary[]>([]),[session,setSession]=useState<CoworkSession|null>(null)
  const [skills,setSkills]=useState<CoworkSkill[]>([]),[goal,setGoal]=useState(''),[message,setMessage]=useState(''),[notice,setNotice]=useState('')
  const [detail,setDetail]=useState<'concise'|'rich'>('rich'),[effort,setEffort]=useState<'low'|'medium'|'high'>('medium'),[busy,setBusy]=useState(false)
  const [permissionOpen,setPermissionOpen]=useState(false),[manualPath,setManualPath]=useState(''),[paperQuery,setPaperQuery]=useState(''),[paperCandidates,setPaperCandidates]=useState<any[]>([])
  const endRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null)
  const loadSessions=async()=>{const rows=await api<CoworkSessionSummary[]>('/api/cowork/sessions');setSessions(rows)}
  useEffect(()=>{void Promise.all([loadSessions(),api<CoworkSkill[]>('/api/cowork/skills').then(setSkills)]).catch(error=>setNotice(error.message))},[])
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[session?.messages.length])
  const refresh=async(id=session?.id)=>{if(!id)return;const current=await api<CoworkSession>(`/api/cowork/sessions/${id}`);setSession(current);await loadSessions()}
  const create=async()=>{if(!goal.trim()||busy)return;setBusy(true);setNotice('');try{const created=await api<CoworkSession>('/api/cowork/sessions',{method:'POST',body:JSON.stringify({goal:goal.trim(),response_detail:detail,thinking_effort:effort})});setSession(created);setGoal('');await loadSessions()}catch(error){setNotice(error instanceof Error?error.message:'创建任务失败')}finally{setBusy(false)}}
  const action=async(name:string)=>{if(!session||busy)return;setBusy(true);try{const updated=await api<CoworkSession>(`/api/cowork/sessions/${session.id}/${name}`,{method:'POST'});setSession(updated);await loadSessions()}catch(error){setNotice(error instanceof Error?error.message:'操作失败')}finally{setBusy(false)}}
  const send=async()=>{if(!session||!message.trim()||busy)return;const value=message.trim();setMessage('');setBusy(true);try{const updated=await api<CoworkSession>(`/api/cowork/sessions/${session.id}/messages`,{method:'POST',body:JSON.stringify({content:value,attachments:[]})});setSession(updated);await loadSessions()}catch(error){setNotice(error instanceof Error?error.message:'发送失败')}finally{setBusy(false)}}
  const selectSession=async(id:string)=>{setBusy(true);try{setSession(await api<CoworkSession>(`/api/cowork/sessions/${id}`))}finally{setBusy(false)}}
  const grantPath=async(path:string,type:'file'|'folder')=>{if(!session||!path.trim())return;try{const updated=await api<CoworkSession>(`/api/cowork/sessions/${session.id}/grants`,{method:'POST',body:JSON.stringify({resource_type:type,resource_scope:path.trim(),can_read:true,can_write:false,duration:'session'})});setSession(updated);setManualPath('');setPermissionOpen(false)}catch(error){setNotice(error instanceof Error?error.message:'授权失败')}}
  const pickFolder=async()=>{const path=await window.pywebview?.api?.choose_folder?.();if(path)await grantPath(path,'folder');else setPermissionOpen(true)}
  const pickFiles=async()=>{const paths=await window.pywebview?.api?.choose_files?.();if(paths?.length){for(const path of paths)await grantPath(path,'file')}else fileRef.current?.click()}
  const localFiles=(files:FileList|null)=>{if(!files?.length)return;setNotice('浏览器不会暴露真实路径；桌面版可直接授权文件。当前仅记录附件名称。');setMessage(value=>`${value}${value?'\n':''}附件：${[...files].map(file=>file.name).join('、')}`)}
  const revoke=async(id:string)=>{if(!session)return;setSession(await api<CoworkSession>(`/api/cowork/sessions/${session.id}/grants/${id}`,{method:'DELETE'}))}
  const searchPaper=async()=>{if(paperQuery.trim().length<2)return;setBusy(true);try{const result=await api<{items:any[]}>(`/api/library/search?q=${encodeURIComponent(paperQuery.trim())}&limit=8`);setPaperCandidates(result.items)}catch(error){setNotice(error instanceof Error?error.message:'检索失败')}finally{setBusy(false)}}
  const importPaper=async(candidate:any)=>{try{await api('/api/library/import',{method:'POST',body:JSON.stringify(candidate)});setPaperCandidates(items=>items.map(item=>item.identity===candidate.identity?{...item,in_library:true}:item));setNotice(`已导入《${candidate.title}》；永久去重规则由学习库执行。`)}catch(error){setNotice(error instanceof Error?error.message:'导入失败')}}
  const activeTask=session?.tasks[session.tasks.length-1],completed=activeTask?.steps.filter(step=>step.status==='completed').length||0,total=activeTask?.steps.length||0
  const canContinue=session&&['planned','paused','running'].includes(session.status)
  const latestSources=useMemo(()=>session?.messages.flatMap(item=>item.sources)||[],[session])

  return <div className="cowork-shell">
    <aside className="cowork-history"><header><div><History/><strong>协作任务</strong></div><button aria-label="新建任务" onClick={()=>setSession(null)}><Plus/></button></header><div>{sessions.map(item=><button key={item.id} className={session?.id===item.id?'active':''} onClick={()=>selectSession(item.id)}><i className={item.status}/><span><strong>{item.title}</strong><small>{statusLabel[item.status]||item.status} · {new Date(item.updated_at).toLocaleDateString()}</small></span><ChevronRight/></button>)}</div><footer><ShieldCheck/><span>本地优先<br/><small>默认拒绝未授权资料</small></span></footer></aside>
    {!session?<main className="cowork-start"><div className="cowork-intro"><span>RESEARCH COWORK</span><h1>把研究目标交给一个<br/>可监督的本地 Agent</h1><p>选择最小资料范围，审阅计划与每次写入，让 PaperMorrow 持续推进文献、实验、笔记和汇报任务。</p></div><section className="cowork-goal-box"><textarea autoFocus value={goal} onChange={event=>setGoal(event.target.value)} placeholder="描述你想完成的研究目标，例如：比较三篇 Agent Memory 论文，形成证据表并生成组会汇报大纲…" onKeyDown={event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey))void create()}}/><div className="cowork-goal-actions"><button onClick={pickFiles}><Paperclip/>文件</button><button onClick={pickFolder}><FolderOpen/>文件夹</button><span/><label>回答<select value={detail} onChange={event=>setDetail(event.target.value as any)}><option value="concise">简洁</option><option value="rich">丰富</option></select></label><label>思考<select value={effort} onChange={event=>setEffort(event.target.value as any)}><option value="low">快速</option><option value="medium">标准</option><option value="high">深入</option></select></label><button className="cowork-send" disabled={!goal.trim()||busy} onClick={create}>{busy?<LoaderCircle className="spin"/>:<ArrowUp/>}</button></div></section><div className="cowork-starters"><article><BookOpen/><strong>文献与证据</strong><span>专题综述、精读、引用核验</span></article><article><Wrench/><strong>实验与复现</strong><span>异常检查、对比与准备清单</span></article><article><Box/><strong>研究产物</strong><span>PPT 大纲、报告、表格与笔记</span></article></div><div className="cowork-skill-strip">{skills.slice(0,5).map(skill=><span key={skill.id} title={`${skill.source} · ${skill.license}`}><Check/>{skill.description}</span>)}</div></main>:
    <main className="cowork-workspace"><header className="cowork-workspace-head"><div><span>RESEARCH COWORK · {statusLabel[session.status]||session.status}</span><h2>{session.title}</h2></div><div>{session.status==='running'?<button onClick={()=>action('pause')}><Pause/>暂停</button>:canContinue?<button className="primary" onClick={()=>action(session.status==='paused'?'resume':'run-next')}><Play/>{session.status==='paused'?'继续':'运行下一步'}</button>:null}{session.status!=='cancelled'&&session.status!=='completed'&&<button className="danger" onClick={()=>action('cancel')}><Square/>停止</button>}</div></header>
      <div className="cowork-permission-bar"><ShieldCheck/><span><strong>当前授权</strong>{session.grants.length?session.grants.map(item=>`${resourceLabel[item.resource_type]||item.resource_type}：${item.resource_scope}`).join(' · '):'尚未授权额外资料，仅可使用会话内容'}</span><button onClick={()=>setPermissionOpen(true)}>调整</button></div>
      <div className="cowork-columns"><section className="cowork-thread"><div className="cowork-plan-card"><header><div><strong>任务计划</strong><span>{completed}/{total} 已完成</span></div><i><b style={{width:`${total?completed/total*100:0}%`}}/></i></header>{activeTask?.steps.map(step=><article key={step.id} className={step.status}><span>{step.status==='completed'?<Check/>:step.status==='running'?<LoaderCircle className="spin"/>:<Circle/>}</span><div><strong>{step.position}. {step.title}</strong><p>{step.result_summary||step.description}</p></div>{['failed','paused','cancelled'].includes(step.status)&&step.retry_count<2&&<button onClick={()=>api<CoworkSession>(`/api/cowork/sessions/${session.id}/steps/${step.id}/retry`,{method:'POST'}).then(setSession)}><RotateCcw/>重试</button>}</article>)}</div>
        <div className="cowork-messages">{session.messages.map(item=><article key={item.id} className={`cowork-message ${item.role}`}><header><span>{item.role==='assistant'?'PaperMorrow Agent':'你'}</span><time>{new Date(item.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></header>{item.blocks.map((block,index)=><div key={index}>{block.type==='markdown'?<ReactMarkdown remarkPlugins={[remarkGfm]}>{block.text||''}</ReactMarkdown>:block.text}</div>)}{item.sources.length>0&&<footer>{item.sources.map((source,index)=><span key={index}>[{source.id||index+1}] {source.title}</span>)}</footer>}{item.role==='assistant'&&<button className="cowork-save"><NotebookPen/>逐段存入笔记</button>}</article>)}{busy&&<div className="cowork-busy"><LoaderCircle className="spin"/>Agent 正在推进一个可验证步骤…</div>}<div ref={endRef}/></div>
        <div className="cowork-compose"><textarea value={message} onChange={event=>setMessage(event.target.value)} placeholder="补充要求、修订计划或询问当前进度…" onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}}/><div><button onClick={pickFiles}><Paperclip/>附件</button><button onClick={pickFolder}><FolderOpen/>文件夹</button><span>Enter 发送 · Shift + Enter 换行</span><button className="cowork-send" disabled={!message.trim()||busy} onClick={send}><ArrowUp/></button></div></div></section>
        <aside className="cowork-inspector"><section><header><FileLock2/><strong>资料与权限</strong></header>{session.grants.length?session.grants.map(item=><article key={item.id}><span>{resourceLabel[item.resource_type]||item.resource_type}</span><strong>{item.resource_scope}</strong><small>{item.can_write?'可读写':'只读'} · {item.duration==='session'?'仅本次':'长期'}</small><button aria-label="撤销授权" onClick={()=>revoke(item.id)}><X/></button></article>):<p>没有额外资料授权。Agent 不会读取你的全部笔记、项目或文件。</p>}</section><section><header><Wrench/><strong>工具与审批</strong></header>{session.tool_calls.length?session.tool_calls.map(item=><article key={item.id}><span className={`risk ${item.risk_level}`}>{item.risk_level}</span><strong>{item.tool_name}</strong><small>{item.approval_status} · {item.status}</small></article>):<p>尚未调用工具。写入与外部操作会先出现审批预览。</p>}</section><section><header><Box/><strong>产物</strong></header>{session.artifacts.length?session.artifacts.map(item=><article key={item.id}><File/><strong>{item.title}</strong><small>{item.type}</small></article>):<p>生成的 PPT、报告、表格、笔记与导入论文会集中在这里。</p>}</section><section><header><Search/><strong>论文候选预览</strong></header><div className="cowork-paper-search"><input value={paperQuery} onChange={event=>setPaperQuery(event.target.value)} onKeyDown={event=>event.key==='Enter'&&searchPaper()} placeholder="DOI、arXiv URL 或标题"/><button onClick={searchPaper}><Search/></button></div>{paperCandidates.map(item=><article className="paper-candidate" key={item.identity}><strong>{item.title}</strong><small>{item.doi||item.arxiv_id||item.source} · {item.abstract?'仅摘要':'仅元数据'}</small><button disabled={item.in_library} onClick={()=>importPaper(item)}>{item.in_library?'已在学习库':'预览后导入'}</button></article>)}</section><section><header><BookOpen/><strong>来源</strong></header>{latestSources.length?latestSources.map((item,index)=><article key={index}><strong>[{item.id||index+1}] {item.title}</strong><small>{item.locator||'会话来源'}</small></article>):<p>引用论文事实时，来源编号与证据范围会显示在这里。</p>}</section></aside></div></main>}
    {permissionOpen&&session&&<div className="cowork-modal" onMouseDown={()=>setPermissionOpen(false)}><section onMouseDown={event=>event.stopPropagation()}><header><div><ShieldCheck/><span><strong>调整本任务权限</strong><small>默认只读、仅本会话；写入仍需单独审批</small></span></div><button onClick={()=>setPermissionOpen(false)}><X/></button></header><button className="picker" onClick={pickFolder}><FolderOpen/><span><strong>选择文件夹</strong><small>允许读取根目录内的非隐藏资料，阻止符号链接逃逸</small></span></button><button className="picker" onClick={pickFiles}><File/><span><strong>选择文件</strong><small>密钥、.env 与凭据文件始终拒绝</small></span></button><label>或输入本机绝对路径<div><input value={manualPath} onChange={event=>setManualPath(event.target.value)} placeholder="/Users/name/research/project"/><button onClick={()=>grantPath(manualPath,'folder')}>只读授权</button></div></label><p>论文、笔记、项目与实验的对象级权限将在引用选择器中逐项加入；不会提供“永久允许删除”。</p></section></div>}
    <input ref={fileRef} type="file" multiple hidden onChange={event=>localFiles(event.target.files)}/>{notice&&<div className="cowork-toast" onClick={()=>setNotice('')}><Check/>{notice}</div>}
  </div>
}
