import { useState } from 'react'
import { CalendarClock, Check, Circle, ExternalLink, Flag, Pencil, Plus, Trash2, X } from 'lucide-react'
import { api } from './api'
import type { PlannerTask, SubmissionDeadline } from './types'
import TimezoneSelect, { dateTimeInputInZone, timezoneLabel, zonedDateTimeToIso } from './timezones'
import './planner.css'

type TaskForm={id?:number;title:string;details:string;due_at:string;priority:PlannerTask['priority']}
type DeadlineForm={id?:number;venue_name:string;venue_type:SubmissionDeadline['venue_type'];round_name:string;deadline_at:string;timezone_name:string;domain:string;website_url:string;notes:string;remind_days_before:number;enabled:boolean}
const emptyTask:TaskForm={title:'',details:'',due_at:'',priority:'medium'}
const emptyDeadline=(timezone:string):DeadlineForm=>({venue_name:'',venue_type:'conference',round_name:'',deadline_at:'',timezone_name:timezone,domain:'',website_url:'',notes:'',remind_days_before:14,enabled:true})
const daysUntil=(value:string)=>Math.ceil((new Date(value).getTime()-Date.now())/86_400_000)
const dateInZone=(value:string,timezone:string)=>new Intl.DateTimeFormat(navigator.language,{timeZone:timezone,year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))

export default function PlannerPage({tasks,deadlines,timezone,onTimezoneChange,onChanged}:{tasks:PlannerTask[];deadlines:SubmissionDeadline[];timezone:string;onTimezoneChange:(timezone:string)=>Promise<void>;onChanged:()=>Promise<void>}){
  const [taskForm,setTaskForm]=useState<TaskForm|null>(null)
  const [deadlineForm,setDeadlineForm]=useState<DeadlineForm|null>(null)
  const [showCompleted,setShowCompleted]=useState(false)
  const [completed,setCompleted]=useState<PlannerTask[]>([])
  const [busy,setBusy]=useState(false)
  const loadCompleted=async()=>{const all=await api<PlannerTask[]>('/api/planner/tasks?include_completed=true');setCompleted(all.filter(item=>item.status==='completed'));setShowCompleted(true)}
  const saveTask=async()=>{if(!taskForm?.title.trim())return;setBusy(true);try{await api(taskForm.id?`/api/planner/tasks/${taskForm.id}`:'/api/planner/tasks',{method:taskForm.id?'PUT':'POST',body:JSON.stringify({...taskForm,title:taskForm.title.trim(),due_at:zonedDateTimeToIso(taskForm.due_at,timezone)})});setTaskForm(null);await onChanged()}finally{setBusy(false)}}
  const saveDeadline=async()=>{if(!deadlineForm?.venue_name.trim()||!deadlineForm.deadline_at)return;setBusy(true);try{const body={...deadlineForm,timezone_name:timezone,venue_name:deadlineForm.venue_name.trim(),deadline_at:zonedDateTimeToIso(deadlineForm.deadline_at,timezone),website_url:deadlineForm.website_url||null};await api(deadlineForm.id?`/api/planner/deadlines/${deadlineForm.id}`:'/api/planner/deadlines',{method:deadlineForm.id?'PUT':'POST',body:JSON.stringify(body)});setDeadlineForm(null);await onChanged()}finally{setBusy(false)}}
  const complete=async(item:PlannerTask,status:'pending'|'completed')=>{await api(`/api/planner/tasks/${item.id}`,{method:'PUT',body:JSON.stringify({status})});await onChanged();if(showCompleted)await loadCompleted()}
  const remove=async(kind:'tasks'|'deadlines',id:number)=>{if(!window.confirm('确认删除这条记录？此操作不会影响论文、笔记或项目。'))return;await api(`/api/planner/${kind}/${id}`,{method:'DELETE'});await onChanged()}

  return <section className="planner-page page-content">
    <div className="planner-hero"><div><span className="section-kicker">RESEARCH PLANNER</span><h2>待办与截稿提醒</h2><p>添加下一步行动和投稿日期，在 {timezoneLabel(timezone)} 下统一查看提醒与剩余时间。</p></div><div><button onClick={()=>setTaskForm({...emptyTask})}><Plus/>添加待办</button><button className="primary" onClick={()=>setDeadlineForm(emptyDeadline(timezone))}><CalendarClock/>添加 DDL</button></div></div>
    <div className="planner-grid">
      <section className="planner-card"><header><div><span>TASKS</span><h3>进行中的待办</h3></div><strong>{tasks.length}</strong></header><div className="planner-task-list">
        {tasks.map(item=><article key={item.id} className={`priority-${item.priority}`}><button className="task-check" onClick={()=>complete(item,'completed')} aria-label={`完成 ${item.title}`}><Circle/></button><div><strong>{item.title}</strong>{item.details&&<p>{item.details}</p>}<small><Flag/> {item.priority==='high'?'高优先级':item.priority==='low'?'低优先级':'普通'}{item.due_at&&<> · {dateInZone(item.due_at,timezone)}</>}</small></div><button onClick={()=>setTaskForm({id:item.id,title:item.title,details:item.details,due_at:dateTimeInputInZone(item.due_at,timezone),priority:item.priority})}><Pencil/></button><button onClick={()=>remove('tasks',item.id)}><Trash2/></button></article>)}
        {!tasks.length&&<div className="planner-empty"><Check/><strong>没有待处理事项</strong><span>添加下一步行动，让研究计划保持清晰。</span></div>}
      </div><footer><button onClick={showCompleted?()=>setShowCompleted(false):loadCompleted}>{showCompleted?'收起已完成':'查看已完成'}</button></footer>{showCompleted&&<div className="planner-completed">{completed.map(item=><button key={item.id} onClick={()=>complete(item,'pending')}><Check/><span>{item.title}</span><small>恢复</small></button>)}</div>}</section>
      <section className="planner-card"><header><div><span>DEADLINES</span><h3>会议与期刊截稿</h3></div><strong>{deadlines.length}</strong></header><div className="deadline-list">
        {deadlines.map(item=>{const days=daysUntil(item.deadline_at);return <article key={item.id} className={days<0?'past':days<=7?'urgent':days<=30?'soon':''}><div className="deadline-days"><strong>{days<0?'—':days}</strong><span>{days<0?'已截止':'天'}</span></div><div><span>{item.venue_type==='conference'?'会议':'期刊'}{item.domain?` · ${item.domain}`:''}</span><h4>{item.venue_name}</h4><p>{item.round_name||'投稿截止'} · {dateInZone(item.deadline_at,timezone)}</p><small>{timezoneLabel(timezone)} · 提前 {item.remind_days_before} 天提醒</small></div>{item.website_url&&<a href={item.website_url} target="_blank" rel="noreferrer" title="打开来源页面"><ExternalLink/></a>}<button onClick={()=>setDeadlineForm({...item,timezone_name:timezone,deadline_at:dateTimeInputInZone(item.deadline_at,timezone)})}><Pencil/></button><button onClick={()=>remove('deadlines',item.id)}><Trash2/></button></article>})}
        {!deadlines.length&&<div className="planner-empty"><CalendarClock/><strong>还没有截稿提醒</strong><span>从会议或期刊官网核对日期后手动添加。</span></div>}
      </div></section>
    </div>
    {taskForm&&<div className="planner-dialog-backdrop" onMouseDown={()=>setTaskForm(null)}><section className="planner-dialog" onMouseDown={event=>event.stopPropagation()}><header><div><span>TASK</span><h3>{taskForm.id?'编辑待办':'添加待办'}</h3></div><button onClick={()=>setTaskForm(null)}><X/></button></header><label>事项<input autoFocus value={taskForm.title} onChange={event=>setTaskForm({...taskForm,title:event.target.value})} placeholder="例如：复现实验二并整理结果"/></label><label>补充说明<textarea value={taskForm.details} onChange={event=>setTaskForm({...taskForm,details:event.target.value})}/></label><div className="planner-form-row"><label>截止时间<input type="datetime-local" value={taskForm.due_at} onChange={event=>setTaskForm({...taskForm,due_at:event.target.value})}/></label><label>优先级<select value={taskForm.priority} onChange={event=>setTaskForm({...taskForm,priority:event.target.value as TaskForm['priority']})}><option value="high">高</option><option value="medium">普通</option><option value="low">低</option></select></label></div><footer><button onClick={()=>setTaskForm(null)}>取消</button><button className="primary" disabled={busy||!taskForm.title.trim()} onClick={saveTask}>保存待办</button></footer></section></div>}
    {deadlineForm&&<div className="planner-dialog-backdrop" onMouseDown={()=>setDeadlineForm(null)}><section className="planner-dialog deadline-dialog" onMouseDown={event=>event.stopPropagation()}><header><div><span>SUBMISSION DEADLINE</span><h3>{deadlineForm.id?'编辑截稿提醒':'添加会议或期刊 DDL'}</h3></div><button onClick={()=>setDeadlineForm(null)}><X/></button></header><div className="planner-form-row"><label>会议或期刊名称<input autoFocus value={deadlineForm.venue_name} onChange={event=>setDeadlineForm({...deadlineForm,venue_name:event.target.value})} placeholder="例如：CVPR 2027"/></label><label>类型<select value={deadlineForm.venue_type} onChange={event=>setDeadlineForm({...deadlineForm,venue_type:event.target.value as DeadlineForm['venue_type']})}><option value="conference">会议</option><option value="journal">期刊</option></select></label></div><div className="planner-form-row"><label>轮次<input value={deadlineForm.round_name} onChange={event=>setDeadlineForm({...deadlineForm,round_name:event.target.value})} placeholder="Main Track / Round 1"/></label><label>领域<input value={deadlineForm.domain} onChange={event=>setDeadlineForm({...deadlineForm,domain:event.target.value})} placeholder="人工智能、临床医学…"/></label></div><div className="planner-form-row"><label>截稿时间<input type="datetime-local" value={deadlineForm.deadline_at} onChange={event=>setDeadlineForm({...deadlineForm,deadline_at:event.target.value})}/></label><label>统一时区<TimezoneSelect value={timezone} onChange={value=>{setDeadlineForm({...deadlineForm,timezone_name:value});void onTimezoneChange(value)}}/></label></div><div className="planner-form-row"><label>提前提醒<select value={deadlineForm.remind_days_before} onChange={event=>setDeadlineForm({...deadlineForm,remind_days_before:Number(event.target.value)})}>{[1,3,7,14,21,30,60].map(day=><option value={day} key={day}>提前 {day} 天</option>)}</select></label><label>来源 URL<input type="url" value={deadlineForm.website_url} onChange={event=>setDeadlineForm({...deadlineForm,website_url:event.target.value})} placeholder="会议或期刊官网"/></label></div><label>备注<textarea value={deadlineForm.notes} onChange={event=>setDeadlineForm({...deadlineForm,notes:event.target.value})} placeholder="摘要截止、全文截止或材料要求…"/></label><footer><button onClick={()=>setDeadlineForm(null)}>取消</button><button className="primary" disabled={busy||!deadlineForm.venue_name.trim()||!deadlineForm.deadline_at} onClick={saveDeadline}>保存 DDL</button></footer></section></div>}
  </section>
}
