import { useEffect, useMemo, useState } from 'react'
import { BookOpenCheck, ChevronRight, MessageCircle, Plus, Search, Send } from 'lucide-react'
import { api } from './api'
import type { Paper, ResearchProject } from './types'
import './projects.css'

const roleLabels:Record<string,string>={core:'核心',support:'支持',conflict:'冲突',background:'背景',to_verify:'待验证'}
const statusLabels:Record<string,string>={to_screen:'待筛选',to_read:'待读',reading:'阅读中',read_to_organize:'已读待整理',completed:'已完成',shelved:'暂时搁置'}

export default function ProjectsPage(){
  const [projects,setProjects]=useState<ResearchProject[]>([]),[active,setActive]=useState<ResearchProject|null>(null),[library,setLibrary]=useState<Paper[]>([]),[creating,setCreating]=useState(false),[title,setTitle]=useState(''),[question,setQuestion]=useState(''),[chat,setChat]=useState(''),[answer,setAnswer]=useState<any|null>(null)
  const load=async()=>{const list=await api<ResearchProject[]>('/api/projects');setProjects(list);if(active){const fresh=await api<ResearchProject>(`/api/projects/${active.id}`);setActive(fresh)}}
  useEffect(()=>{load();api<Paper[]>('/api/library/papers').then(setLibrary)},[])
  const available=useMemo(()=>library.filter(p=>!active?.papers?.some(link=>link.paper_id===p.id)),[library,active])
  const create=async()=>{const item=await api<ResearchProject>('/api/projects',{method:'POST',body:JSON.stringify({title,research_question:question})});setCreating(false);setTitle('');setQuestion('');setActive(item);await load()}
  const open=async(id:number)=>setActive(await api(`/api/projects/${id}`))
  const addPaper=async(paperId:number)=>{setActive(await api(`/api/projects/${active!.id}/papers`,{method:'POST',body:JSON.stringify({paper_id:paperId,role:'to_verify',reading_status:'to_screen'})}))}
  const updatePaper=async(paperId:number,values:any)=>setActive(await api(`/api/projects/${active!.id}/papers/${paperId}`,{method:'PUT',body:JSON.stringify(values)}))
  const ask=async()=>{const result=await api(`/api/projects/${active!.id}/chat`,{method:'POST',body:JSON.stringify({message:chat})});setAnswer(result);setChat('')}
  if(active)return <section className="page-content project-page"><button className="project-back" onClick={()=>{setActive(null);load()}}>← 所有项目</button><header className="project-hero"><div><span className="section-kicker">RESEARCH PROJECT</span><h2>{active.title}</h2><p>{active.research_question||'尚未填写研究问题'}</p></div><div><strong>{active.papers?.length||0}</strong><span>项目论文</span></div></header><div className="project-columns"><main><section className="project-panel"><h3>阅读队列</h3>{active.papers?.length?<div className="project-papers">{active.papers.map(link=><article key={link.paper_id}><div><span>{roleLabels[link.role]}</span><strong>{link.title_zh||link.title}</strong><small>{link.title}</small></div><select value={link.role} onChange={e=>updatePaper(link.paper_id,{role:e.target.value})}>{Object.entries(roleLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={link.reading_status} onChange={e=>updatePaper(link.paper_id,{reading_status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></article>)}</div>:<p className="project-muted">从学习库加入核心论文，建立阅读队列。</p>}</section><section className="project-panel"><h3>从学习库加入</h3><div className="project-add-list">{available.slice(0,8).map(p=><button key={p.id} onClick={()=>addPaper(p.id)}><Plus/><span>{p.title_zh||p.title_en}</span></button>)}</div></section></main><aside><section className="project-panel project-chat"><h3><MessageCircle/>项目级 AI 对话</h3><p>只检索本项目的论文、笔记、专题调研和 Wiki，结果标注来源。</p><div className="project-chat-input"><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="询问当前项目的证据…"/><button disabled={!chat.trim()} onClick={ask}><Send/></button></div>{answer&&<div className="project-answer"><p>{answer.answer}</p><div>{answer.sources.map((s:any,i:number)=><span key={i}>{s.source_label} · {s.title}</span>)}</div></div>}</section><section className="project-panel"><h3>研究状态</h3><label>当前结论<textarea value={active.current_conclusion} onChange={e=>setActive({...active,current_conclusion:e.target.value})} onBlur={()=>api(`/api/projects/${active.id}`,{method:'PUT',body:JSON.stringify({current_conclusion:active.current_conclusion})})}/></label><label>下一篇阅读建议<textarea value={active.next_reading_suggestion} onChange={e=>setActive({...active,next_reading_suggestion:e.target.value})} onBlur={()=>api(`/api/projects/${active.id}`,{method:'PUT',body:JSON.stringify({next_reading_suggestion:active.next_reading_suggestion})})}/></label></section></aside></div></section>
  return <section className="page-content project-page"><header className="project-list-head"><div><span className="section-kicker">PROJECT WORKSPACE</span><h2>研究项目</h2><p>把研究问题、论文角色、阅读队列、笔记、专题调研和 DeepWiki 汇集到一个可追溯工作流。</p></div><button className="primary" onClick={()=>setCreating(true)}><Plus/>新建项目</button></header>{creating&&<div className="project-create"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="项目名称"/><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="研究问题"/><button disabled={!title.trim()} onClick={create}>创建</button></div>}<div className="project-list">{projects.map(p=><button key={p.id} onClick={()=>open(p.id)}><BookOpenCheck/><div><strong>{p.title}</strong><span>{p.research_question||'等待定义研究问题'}</span></div><ChevronRight/></button>)}</div>{!projects.length&&!creating&&<div className="project-empty"><Search/><h3>从一个明确问题开始</h3><p>创建项目后，再从现有学习库加入论文。</p></div>}</section>
}
